#!/usr/bin/env bash
# This script transfers a file from our client to a server.

if [[ $# == 4 ]]
then
    echo "put $1" | sftp -i "$4" "$3"@"$2"
else
    echo $#
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi
