#!/usr/bin/env bash
# This script installs and configures an nginx web server


# Update package list and install nginx
sudo apt-get update
sudo apt-get install -y nginx

# Configure firewall
sudo ufw allow 'Nginx HTTP'

# Create a simple file with the string "Hello World!"
echo "Hello, World!" > sudo tee /var/www/html/index.html

# Restart Nginx to apply changes (without using systemctl)
sudo service nginx restart
