#!/usr/bin/env bash
# This script Configure an Nginx server to have a custom 404 page.

sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html

redirect_string="server_name _;\n\tlocation /redirect_me {\n\t\treturn 301 /;\n\t}"
sudo sed -i "s.server_name _;.$redirect_string." /etc/nginx/sites-enabled/default

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

not_found_string="server_name _;\n\troot /var/www/html;\n\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\tinternal;\n\t}"
sudo sed -i "s|server_name _;|$not_found_string|" /etc/nginx/sites-enabled/default

sudo service nginx restart
