#!/usr/bin/env bash
# This script configure web-02 to be identical to web-01 and Configure Nginx so that its HTTP response contains a custom header.

# install nginx
sudo apt-get update
sudo apt-get install -y nginx

# Setup our index and 404 files
echo "Hello World!" | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# Configure nginx configuration file
replace_string="server_name _;\n\tlocation /redirect_me {\n\t\treturn 301 /;\n\t}\n\terror_page 404 /404.html;\n\tlocation /404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}\n\tset \$server_name_var \$server_name;\n\tadd_header X-Server-Name \$server_name_var;"

sudo sed -i "s|server_name _;|${replace_string}|" /etc/nginx/sites-enabled/default

sudo service nginx restart
