#!/usr/bin/env bash
# This script configures Nginx to listen on port 80
sudo apt-get update
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'
# Setting the default configuration file
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
