#!/usr/bin/env bash
# This script configures nginx to listen on port 80  nginx (service (init) must say that nginx is not running)
sudo sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
sudo service nginx restart
pkill -o nginx
