#!/usr/bin/env bash
#This bash script displays the PID, along with the process name,
#of processes whose name contain the word bash
top -b -n 1 > temp.txt
awk '/bash/ {print $1 " bash"}' temp.txt
rm temp.txt
