#!/usr/bin/env bash
#This script uses while loop to print a string 10 times
#on the 4th iteration, it prints "bad luck"
#on the 8th iteration, it prints "good luck"
#and on the other iteration, it prints "Best School"

i=0
while [ $i -lt 10 ]
do
	if [ $i == 3 ]
	then
		echo "bad luck"
	elif [ $i == 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	i=$((i + 1))
done
